



```{r geo-tsv}
#click `Homo sapiens` in https://www.ncbi.nlm.nih.gov/geo/browse/?view=platforms

geo_tsv <- function(type = c('platforms', 'series'), page = 1, tax_id = '9606') {
    paste0('https://www.ncbi.nlm.nih.gov/geo/browse/?view=', type, '&tax=', tax_id, '&mode=tsv&page=', page, '&display=5000')
}

mcmapply(download.file, geo_tsv('platforms', 1:2), paste0('data-raw/geo-tsv/platform-', 1:2, '.tsv'))
mcmapply(download.file, geo_tsv('series', 1:9),    paste0('data-raw/geo-tsv/series-',   1:9, '.tsv'))
```


```{r GPL-html}
dir('data-raw/GPL-html', full = T) %>% {.[file.size(.) <10]} %>% file.remove

foobar <- function(){
    lem4::platform_human$Accession %>% 
    {setdiff(., dir('data-raw/GPL-html') %>% str_extract('GPL\\d+'))} %>%
    mclapply(. %>% {
        input  <- paste0('https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=', .);
        output <- paste0('data-raw/GPL-html/', ., '.html');
        if (!file.exists(output)) download.file(input, output)
    }, mc.cores = 16);
}
foobar()
```

# legacy

```{r GSE-html, eval=FLASE}
#" GSE which contains multiple GSE (thus more than one GPL)
#" to avoid repetition, these files are no longer needed, following is the code used to parse them
# dir('data-raw/GSE-html', full.names = T) %>% mclapply(. %>% {
# 	tibble(series = str_extract(., 'GSE\\d+'), 
# 		   platform = unique(str_extract_all(read_file(.), '(?<=acc=)GPL\\d+')[[1]])
# 	)
# })

series_not_in_summary <- dir('data-raw/geo-tsv', 'series', full.names = T) %>% 
	lapply(libzhuoer::read_char_tsv) %>% bind_rows() %>% 
	filter(Taxonomy == 'Homo sapiens', str_detect(`Series Type`, '^Expression profiling by array$')) %>% 
	filter(!(Accession %in% filter(lem4::read_summary('data-raw/gds_result.txt'), str_count(platform, 'GPL') == 1L)$accession))

dir('data-raw/GSE-html', full = T) %>% {.[file.size(.) <10]} %>% file.remove

foobar <- function(){
    series_not_in_summary$Accession %>% 
    {setdiff(., dir('data-raw/GSE-html') %>% str_extract('GSE\\d+'))} %>%
    mclapply(. %>% {
        input  <- paste0('https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=', .);
        output <- paste0('data-raw/GSE-html/', ., '.html');
        if (!file.exists(output)) download.file(input, output)
    }, mc.cores = 16);
}
foobar()
```

